services:

  proxy:
    image: reg.ntl.nc/proxy/nginxproxy/nginx-proxy
    ports: 
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - frontend

  app1:
    image: reg.ntl.nc/proxy/traefik/whoami
    environment:
      VIRTUAL_HOST: "foo.bar.localhost"
    networks:
      - frontend
      - backend
  app2:
    image: reg.ntl.nc/proxy/library/nginx
    environment:
      VIRTUAL_HOST: "bar.foo.localhost"
    networks:
      - frontend
      - backend

  db:
    image: reg.ntl.nc/proxy/library/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "SuperP@assword"
    networks:
      - backend

networks:
  frontend:
  backend:

